/*
 *   Copyright (c) 2025 
 *   All rights reserved.
 */

// This file will be generated by Supabase CLI
// For now, we'll provide basic types

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          role: 'client' | 'staff' | 'owner' | 'admin';
          first_name: string | null;
          last_name: string | null;
          phone: string | null;
          avatar_url: string | null;
          date_of_birth: string | null;
          marketing_consent: boolean;
          sms_consent: boolean;
          push_token: string | null;
          timezone: string;
          preferred_language: string;
          last_active: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          role?: 'client' | 'staff' | 'owner' | 'admin';
          first_name?: string | null;
          last_name?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          date_of_birth?: string | null;
          marketing_consent?: boolean;
          sms_consent?: boolean;
          push_token?: string | null;
          timezone?: string;
          preferred_language?: string;
          last_active?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          role?: 'client' | 'staff' | 'owner' | 'admin';
          first_name?: string | null;
          last_name?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          date_of_birth?: string | null;
          marketing_consent?: boolean;
          sms_consent?: boolean;
          push_token?: string | null;
          timezone?: string;
          preferred_language?: string;
          last_active?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      shops: {
        Row: {
          id: string;
          owner_id: string;
          name: string;
          description: string | null;
          phone: string | null;
          email: string | null;
          website: string | null;
          logo_url: string | null;
          cover_image_url: string | null;
          currency: string;
          timezone: string;
          booking_window_days: number;
          cancellation_window_hours: number;
          auto_confirm_bookings: boolean;
          loyalty_enabled: boolean;
          reviews_enabled: boolean;
          waitlist_enabled: boolean;
          online_payments_enabled: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          name: string;
          description?: string | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          logo_url?: string | null;
          cover_image_url?: string | null;
          currency?: string;
          timezone?: string;
          booking_window_days?: number;
          cancellation_window_hours?: number;
          auto_confirm_bookings?: boolean;
          loyalty_enabled?: boolean;
          reviews_enabled?: boolean;
          waitlist_enabled?: boolean;
          online_payments_enabled?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          name?: string;
          description?: string | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          logo_url?: string | null;
          cover_image_url?: string | null;
          currency?: string;
          timezone?: string;
          booking_window_days?: number;
          cancellation_window_hours?: number;
          auto_confirm_bookings?: boolean;
          loyalty_enabled?: boolean;
          reviews_enabled?: boolean;
          waitlist_enabled?: boolean;
          online_payments_enabled?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      // Add more tables as needed
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      user_role: 'client' | 'staff' | 'owner' | 'admin';
      appointment_status: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
      // Add more enums as needed
    };
  };
}
