name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information about your request.

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New mobile screen/flow
        - Backend/API enhancement
        - Database feature
        - UI/UX improvement
        - Performance optimization
        - Developer experience
        - Third-party integration
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current pain point?
      placeholder: Describe the problem or limitation you're experiencing...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: Describe your solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe alternatives you've considered...

  - type: textarea
    id: userflow
    attributes:
      label: User Flow
      description: If applicable, describe the user flow for this feature
      placeholder: |
        1. User navigates to...
        2. User taps on...
        3. System shows...
        4. User can then...

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What specific criteria must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve user experience
        - High - Important for core functionality
        - Critical - Blocking major use case
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Designs
      description: Include any mockups, wireframes, or design references
      placeholder: Drag and drop images here or provide links to designs

  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations
      description: Any technical constraints or implementation details to consider?
      placeholder: Consider performance, security, scalability, etc.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, links, or examples about the feature request here.
